name = "crc"
description = "Cyclic Redundancy Check (CRC) implementation"
version = "0.1.0-dev"

authors = ["Miko Elbrecht"]
maintainers = ["Miko Elbrecht <pmt.mailservice@gmail.com>"]
maintainers-logins = ["meownium"]
licenses = "GPL-3.0-or-later"
website = "https://javart.zip"
tags = ["crc", "crc32", "redundancy", "error", "checking", "error-checking"]
